modLoader = "javafml"
loaderVersion = "[37,)"

authors = "chylex"
license = "Unlicense"
issueTrackerURL = "https://github.com/chylex/Minecraft-View-Distance-Workaround/issues"

[[mods]]
modId = "viewdistanceworkaround"
version = "${version}"
displayName = "${name}"
description = "Delays sending chunks on login and adds /view-distance command"

[[dependencies.viewdistanceworkaround]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.viewdistanceworkaround]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"
